#!/bin/bash

CONFIG_PATH=/data/options.json

DATA_PATH=$(jq --raw-output '.data_path' $CONFIG_PATH)

# Check if config exists already
# Copy example configuration if not exists
mkdir -p $DATA_PATH
if [ ! -f $DATA_PATH/configuration.yaml ]; then
  cp ./etc/s0pcm/configuration.yaml $DATA_PATH/configuration.yaml
fi

# Configure S0PCM config with the add-on variables
# mqtt_port=$(jq --raw-output '.device' $CONFIG_PATH)
# sed -i '~mqtt:~,~mqtt:~ s~port.*~port: ${device_port}~g' "$DATA_PATH/configuration - Copy.yaml"
device_port=$(jq --raw-output '.device' $CONFIG_PATH)
sed -i "/serial:/,/serial:/ s~port.*~port: ${device_port}~g" "$DATA_PATH/configuration - Copy.yaml"

# Start s0pcm-reader
echo "[INFO] Start S0PCM-reader"
/usr/local/bin/python /usr/bin/s0pcm-reader.py -c $DATA_PATH

if [ -f $DATA_PATH/.noexit ]; then
  sleep 7d
fi